# Generated by Django 5.2.7 on 2025-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhome', 'Townhome'), ('office', 'Office / Commercial')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('rooms', models.JSONField(default=list)),
                ('project_type', models.CharField(choices=[('new_build', 'New Build'), ('renovation', 'Renovation'), ('decoration', 'Decoration / Styling')], max_length=50)),
                ('project_stage', models.CharField(choices=[('planning', 'Just starting to plan'), ('floor_plan', 'Have floor plan / drawings'), ('construction', 'Construction has started'), ('almost_finished', 'Almost finished — need design help')], max_length=50)),
                ('preferred_style', models.CharField(max_length=100)),
                ('favorite_colors', models.CharField(blank=True, max_length=200)),
                ('disliked_colors', models.CharField(blank=True, max_length=200)),
                ('atmosphere', models.CharField(blank=True, max_length=200)),
                ('inspiration', models.FileField(blank=True, null=True, upload_to='media/')),
                ('budget', models.CharField(choices=[('under_15k', 'Under $15,000'), ('15_30k', '$15–30K'), ('30_60k', '$30–60K'), ('60k_plus', '$60K+'), ('not_sure', 'Not sure yet')], max_length=50)),
                ('timeline', models.CharField(choices=[('1_2_months', 'Within 1–2 months'), ('3_6_months', '3–6 months'), ('flexible', 'Flexible')], max_length=50)),
                ('involvement', models.CharField(choices=[('full_service', 'Full service — you handle everything'), ('collaboration', 'Collaboration — we decide together'), ('e_design', 'Professional guidance (E-Design)')], max_length=50)),
                ('hear_about', models.CharField(choices=[('instagram', 'Instagram'), ('google', 'Google'), ('friend', 'Realtor / Friend'), ('other', 'Other')], max_length=50)),
                ('hear_about_other', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_method', models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
