# Generated by Django 5.2.7 on 2025-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('area', models.CharField(max_length=100, verbose_name='Квадратных метров или других величин')),
                ('role', models.TextField(verbose_name='Роль в проекте')),
                ('year', models.CharField(max_length=10, verbose_name='Год выполнения работы')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 5')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 6')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 7')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 8')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 9')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 10')),
            ],
        ),
    ]
